"""Product data MCP server for the agentic banking ecosystem.

Exposes the bank's **financial product catalogue** (current accounts, savings,
children's savings and credit cards) together with the per-customer
``ProductHolding`` records, over the Model Context Protocol. The banking agents
(``customer_support_agent``, ``employee_advisory_agent``, ``credit_card_agent``)
use it to list and explain products, look up what a customer holds, order a new
product and update an existing holding.

Two data sources are loaded once at startup:

* the product catalogue in ``product_catalogue.json`` next to this module (a
  JSON mirror of the catalogue table in ``data/products.md``); and
* the per-customer holdings in the shared ``data/customers.json`` (generated by
  ``scripts/generate_data.py``).

There is no database — these files *are* the source of truth. Every MCP tool
call is expected to be authenticated via Entra ID, and all write tools are
human-in-the-loop. The canonical entities and tool surface are defined in
``data/products.md``.

Run it with::

    python -m src.product_data_mcp_server.server

It serves the streamable-HTTP MCP transport on ``http://127.0.0.1:8093/mcp`` by
default (override with ``PRODUCT_MCP_HOST`` / ``PRODUCT_MCP_PORT``).
"""

from __future__ import annotations

import copy
import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

from fastmcp import FastMCP
from starlette.requests import Request
from starlette.responses import JSONResponse

_CATALOGUE_FILE = Path(__file__).with_name("product_catalogue.json")


def _data_dir() -> Path:
    """Resolve the shared ``data/`` directory (repo root or ``BANK_DATA_DIR``)."""
    override = os.getenv("BANK_DATA_DIR")
    if override:
        return Path(override)
    # server.py -> product_data_mcp_server -> src -> <repo root>/data
    return Path(__file__).resolve().parents[2] / "data"


@lru_cache(maxsize=1)
def _catalogue() -> list[dict[str, Any]]:
    """Load and cache the product catalogue."""
    with _CATALOGUE_FILE.open("r", encoding="utf-8") as fh:
        return json.load(fh)["products"]


@lru_cache(maxsize=1)
def _customers() -> list[dict[str, Any]]:
    """Load and cache the customers (with nested product holdings)."""
    with (_data_dir() / "customers.json").open("r", encoding="utf-8") as fh:
        return json.load(fh)["customers"]


def _find_product(product_code: str) -> Optional[dict[str, Any]]:
    code = product_code.strip().upper()
    for product in _catalogue():
        if product["product_code"].upper() == code:
            return product
    # Fall back to a case-insensitive product-name match.
    name = product_code.strip().lower()
    for product in _catalogue():
        if product["product_name"].lower() == name:
            return product
    return None


def _find_customer(customer_id: str) -> Optional[dict[str, Any]]:
    cid = customer_id.strip().upper()
    return next((c for c in _customers() if c["customer_id"].upper() == cid), None)


def _find_holding(account_id: str) -> Optional[dict[str, Any]]:
    aid = account_id.strip().upper()
    for customer in _customers():
        for holding in customer.get("products", []):
            if holding["account_id"].upper() == aid:
                return holding
    return None


def _next_account_id() -> str:
    """Return the next free ``ACC-<6 digits>`` id across all customers."""
    highest = 100000
    for customer in _customers():
        for holding in customer.get("products", []):
            digits = holding["account_id"].split("-")[-1]
            if digits.isdigit():
                highest = max(highest, int(digits))
    return f"ACC-{highest + 1:06d}"


_HOST = os.getenv("PRODUCT_MCP_HOST", "127.0.0.1")
_PORT = int(os.getenv("PRODUCT_MCP_PORT", "8093"))


def _build_auth():
    """Build the FastMCP Microsoft Entra ID JWT auth provider, or ``None``.

    Enabled only when ``ENTRA_AUTH_ENABLED`` is truthy and both the API audience
    (``MCP_AUTH_CLIENT_ID``) and ``AZURE_TENANT_ID`` are set. The provider
    validates incoming Entra access tokens (issuer, audience and JWKS signature)
    inside the app itself — no Container Apps Easy Auth and no client secret.
    No scope is required, so both delegated (user) and app-only (managed
    identity) tokens are accepted. Returns ``None`` to run anonymously (local
    development, or auth toggled off).
    """
    enabled = os.getenv("ENTRA_AUTH_ENABLED", "false").strip().lower() in {
        "1", "true", "yes", "on",
    }
    client_id = os.getenv("MCP_AUTH_CLIENT_ID", "").strip()
    tenant_id = os.getenv("AZURE_TENANT_ID", "").strip()
    if not (enabled and client_id and tenant_id):
        return None
    from fastmcp.server.auth import RemoteAuthProvider
    from fastmcp.server.auth.providers.azure import AzureJWTVerifier
    from pydantic import AnyHttpUrl

    base_url = os.getenv("MCP_PUBLIC_BASE_URL", "").strip() or f"http://{_HOST}:{_PORT}"
    verifier = AzureJWTVerifier(client_id=client_id, tenant_id=tenant_id)
    return RemoteAuthProvider(
        token_verifier=verifier,
        authorization_servers=[
            AnyHttpUrl(f"https://login.microsoftonline.com/{tenant_id}/v2.0")
        ],
        base_url=base_url,
    )


mcp = FastMCP(
    name="product_data",
    instructions=(
        "Financial product catalogue and per-customer product holdings. Use "
        "these tools to list and explain products (current accounts, savings, "
        "children's savings, credit cards), look up what a customer holds, "
        "order a new product and update a holding. Use 'detect_opportunities' to "
        "proactively surface optimisation ideas — idle cash on a low-interest "
        "account (with an estimated annual interest gain) or a credit-card "
        "candidate when the customer holds none. Interest rates are annual "
        "percentages and all monetary values are in EUR; detailed conditions "
        "are in the linked knowledge files. The 'order_product' and "
        "'update_holding' tools are write operations and require explicit human "
        "approval (human-in-the-loop) before they commit."
    ),
    auth=_build_auth(),
)


@mcp.custom_route("/health", methods=["GET"])
async def health_check(_: Request) -> JSONResponse:
    """Readiness probe endpoint — returns 200 OK when the server is up."""
    return JSONResponse({"status": "ok"})


@mcp.tool()
def list_products(category: Optional[str] = None) -> list[dict[str, Any]]:
    """List the financial product catalogue, optionally filtered by category.

    Args:
        category: Optional category filter — ``current_account``, ``savings``,
            ``childrens_savings`` or ``credit_card`` (case-insensitive). Omit to
            list every product.

    Each product includes its code, name, category, currency, annual interest
    rate, annual fee, minimum deposit and a reference to the knowledge file that
    documents its full conditions.
    """
    products = _catalogue()
    if category:
        needle = category.strip().lower()
        products = [p for p in products if p["category"] == needle]
    return copy.deepcopy(products)


@mcp.tool()
def get_product(product_code: str) -> dict[str, Any]:
    """Get a single product definition by code (or exact name).

    Args:
        product_code: The product code (e.g. ``GOLDCARD``) or exact product name
            (e.g. ``GoldCard``).

    Returns the product's catalogue fields including the ``knowledge_ref`` path
    that documents its conditions. If no product matches, an ``error`` field is
    returned instead.
    """
    product = _find_product(product_code)
    if product is None:
        return {"error": f"No product matched '{product_code}'."}
    return copy.deepcopy(product)


@mcp.tool()
def list_holdings(customer_id: str) -> list[dict[str, Any]]:
    """List the product holdings a customer currently has.

    Args:
        customer_id: The customer id, format ``CUST-1001``.

    Each holding includes the account id, product, IBAN or masked card number,
    balance, credit limit (cards) and status. Returns an empty list if the
    customer has no holdings or does not exist.
    """
    customer = _find_customer(customer_id)
    if customer is None:
        return []
    return copy.deepcopy(customer.get("products", []))


def _round2(value: float) -> float:
    """Round a monetary amount to 2 decimal places."""
    return round(float(value), 2)


def _best_savings_product(exclude_codes: set[str]) -> Optional[dict[str, Any]]:
    """Return the highest-interest savings product not already held."""
    savings = [
        p for p in _catalogue()
        if p["category"] == "savings"
        and p["product_code"].upper() not in exclude_codes
        and p.get("interest_rate") is not None
    ]
    if not savings:
        return None
    return max(savings, key=lambda p: p["interest_rate"])


def _cheapest_credit_card() -> Optional[dict[str, Any]]:
    """Return the credit card with the lowest annual fee (entry card)."""
    cards = [p for p in _catalogue() if p["category"] == "credit_card"]
    if not cards:
        return None
    return min(cards, key=lambda p: p.get("annual_fee", 0) or 0)


@mcp.tool()
def detect_opportunities(customer_id: str,
                         liquidity_buffer: float = 3000.0,
                         min_idle_balance: float = 10000.0,
                         min_annual_gain: float = 25.0) -> dict[str, Any]:
    """Detect proactive optimisation opportunities for a customer (read).

    Powers the agent's *proactive impulse*: it scans the customer's holdings and
    the product catalogue and flags concrete, personalised opportunities the
    agent can offer (after asking the customer's permission). Two kinds:

    * ``idle_cash`` — money sitting on a low- or zero-interest holding (typically
      the current account) that could earn more in the best available savings
      product. The estimated **annual interest gain** is computed on the amount
      above ``liquidity_buffer`` at the rate difference.
    * ``credit_card`` — the customer holds no credit card, so an entry card is a
      candidate. The concrete cost/benefit must be validated by the agent
      against the customer's spending (use ``summarize_spending`` on the customer
      data server); this tool only surfaces the candidate and its annual fee.

    Args:
        customer_id: The customer id, format ``CUST-1001``.
        liquidity_buffer: Cash to leave on the current account for day-to-day
            liquidity when computing the movable idle amount (default 3000).
        min_idle_balance: Only flag a holding whose balance exceeds this
            (default 10000).
        min_annual_gain: Only flag an idle-cash opportunity whose estimated
            annual gain is at least this (default 25 EUR).

    Returns ``{customer_id, opportunities[], count}``. Each opportunity carries
    the evidence (account, balances, rates) and, for idle cash, the
    ``estimated_annual_gain``. Returns an ``error`` if the customer is unknown.
    """
    customer = _find_customer(customer_id)
    if customer is None:
        return {"error": f"No customer matched '{customer_id}'."}

    holdings = customer.get("products", [])
    held_codes = {h.get("product_code", "").upper() for h in holdings}
    best = _best_savings_product(held_codes) or _best_savings_product(set())
    best_rate = float(best["interest_rate"]) if best else 0.0

    opportunities: list[dict[str, Any]] = []

    # 1) Idle cash on low-/zero-interest holdings (current accounts and savings
    #    that pay materially less than the best available savings rate).
    for holding in holdings:
        category = holding.get("category")
        if category not in {"current_account", "savings"}:
            continue
        balance = float(holding.get("balance", 0.0))
        if balance < min_idle_balance:
            continue
        current_rate = 0.0
        product = _find_product(holding.get("product_code", ""))
        if product and product.get("interest_rate") is not None:
            current_rate = float(product["interest_rate"])
        if best is None or best_rate <= current_rate:
            continue
        # Keep a liquidity buffer only on the transactional current account.
        buffer = liquidity_buffer if category == "current_account" else 0.0
        movable = max(0.0, balance - buffer)
        gain = movable * (best_rate - current_rate) / 100.0
        if gain < min_annual_gain:
            continue
        opportunities.append({
            "type": "idle_cash",
            "account_id": holding["account_id"],
            "product_name": holding.get("product_name"),
            "category": category,
            "balance": _round2(balance),
            "current_interest_rate": current_rate,
            "liquidity_buffer": _round2(buffer),
            "movable_amount": _round2(movable),
            "recommended_product": {
                "product_code": best["product_code"],
                "product_name": best["product_name"],
                "interest_rate": best_rate,
                "knowledge_ref": best.get("knowledge_ref"),
            },
            "estimated_annual_gain": _round2(gain),
            "rationale": (
                f"{_round2(movable)} EUR earning {current_rate}% could move to "
                f"{best['product_name']} at {best_rate}% for about "
                f"{_round2(gain)} EUR more interest per year."
            ),
        })

    # 2) No credit card held -> entry card candidate (benefit validated by the
    #    agent against actual spending via summarize_spending).
    if not any(h.get("category") == "credit_card" for h in holdings):
        card = _cheapest_credit_card()
        if card is not None:
            opportunities.append({
                "type": "credit_card",
                "reason": "no_card_held",
                "recommended_product": {
                    "product_code": card["product_code"],
                    "product_name": card["product_name"],
                    "annual_fee": card.get("annual_fee"),
                    "knowledge_ref": card.get("knowledge_ref"),
                },
                "note": (
                    "Validate the cost/benefit against the customer's spending "
                    "behaviour (summarize_spending) before recommending; only "
                    "worthwhile if card benefits outweigh the annual fee."
                ),
            })

    # Largest estimated gain first, idle-cash opportunities ahead of the card.
    opportunities.sort(
        key=lambda o: o.get("estimated_annual_gain", 0.0), reverse=True
    )
    return {
        "customer_id": customer["customer_id"],
        "opportunities": opportunities,
        "count": len(opportunities),
    }


@mcp.tool()
def order_product(customer_id: str, product_code: str,
                  confirm: bool = False) -> dict[str, Any]:
    """Order a new product for a customer (write — human-in-the-loop).

    This is a **write** operation and requires explicit human approval. Call it
    first with ``confirm=False`` (the default) to receive a preview of the
    holding that would be opened; present that preview to the human and only
    re-call with ``confirm=True`` once approval has been granted.

    Args:
        customer_id: The customer id, format ``CUST-1001``.
        product_code: The product to order (e.g. ``GOLDCARD``).
        confirm: Set to ``True`` only after a human has approved the preview.

    Returns a ``pending_approval`` preview when ``confirm`` is ``False``, or the
    newly created holding once committed.
    """
    customer = _find_customer(customer_id)
    if customer is None:
        return {"error": f"No customer matched '{customer_id}'."}
    product = _find_product(product_code)
    if product is None:
        return {"error": f"No product matched '{product_code}'."}

    is_card = product["category"] == "credit_card"
    new_holding = {
        "account_id": _next_account_id(),
        "customer_id": customer["customer_id"],
        "product_code": product["product_code"],
        "product_name": product["product_name"],
        "category": product["category"],
        "iban": None if is_card else "PENDING-ASSIGNMENT",
        "card_number": "PENDING-ASSIGNMENT" if is_card else None,
        "balance": 0.0,
        "credit_limit": 1000 if is_card else None,
        "currency": product.get("currency", "EUR"),
        "status": "pending",
    }

    if not confirm:
        return {
            "status": "pending_approval",
            "customer_id": customer["customer_id"],
            "requires": "human approval (call again with confirm=true)",
            "proposed_holding": new_holding,
        }

    # Commit against the in-memory cache. The change lives for the life of the
    # process — deliberately not persisted to disk in this demo.
    new_holding["status"] = "active"
    customer.setdefault("products", []).append(
        {k: v for k, v in new_holding.items() if k != "customer_id"}
    )
    return {"status": "committed", "holding": new_holding}


# Fields a holding is allowed to change through this tool. Identity and money
# fields (account_id, customer_id, product_code, balance) are not editable here.
_EDITABLE_HOLDING_FIELDS = {"status", "credit_limit", "iban", "card_number"}


@mcp.tool()
def update_holding(account_id: str, fields: dict[str, Any],
                   confirm: bool = False) -> dict[str, Any]:
    """Update an existing product holding (write — human-in-the-loop).

    This is a **write** operation and requires explicit human approval. Call it
    first with ``confirm=False`` (the default) to receive a preview of the
    change; present that preview to the human and only re-call with
    ``confirm=True`` once approval has been granted. Only ``status``,
    ``credit_limit``, ``iban`` and ``card_number`` may be changed.

    Args:
        account_id: The account id, format ``ACC-100001``.
        fields: Mapping of field name to new value (subset of ``status``,
            ``credit_limit``, ``iban``, ``card_number``).
        confirm: Set to ``True`` only after a human has approved the preview.

    Returns a ``pending_approval`` preview when ``confirm`` is ``False``, or the
    updated holding once committed.
    """
    holding = _find_holding(account_id)
    if holding is None:
        return {"error": f"No account matched '{account_id}'."}

    invalid = set(fields) - _EDITABLE_HOLDING_FIELDS
    if invalid:
        return {
            "error": f"Fields not editable: {sorted(invalid)}.",
            "editable_fields": sorted(_EDITABLE_HOLDING_FIELDS),
        }
    if not fields:
        return {"error": "No fields supplied to update."}

    changes = {
        key: {"from": holding.get(key), "to": value}
        for key, value in fields.items()
    }

    if not confirm:
        return {
            "status": "pending_approval",
            "account_id": holding["account_id"],
            "requires": "human approval (call again with confirm=true)",
            "changes": changes,
        }

    holding.update(fields)
    return {"status": "committed", "holding": copy.deepcopy(holding),
            "changes": changes}


def main() -> None:
    """Entry point — serve the product data over streamable-HTTP MCP."""
    # ``host_origin_protection`` is FastMCP's DNS-rebinding guard for browser
    # clients hitting localhost dev servers; it rejects any Host header outside
    # 127.0.0.1/localhost with HTTP 421. This server runs behind the Container
    # Apps ingress (which routes by host) and is protected by Entra JWT auth, so
    # the guard is both unnecessary and would block the public FQDN + health
    # probe. Disable it and rely on the ingress + JWT verification instead.
    mcp.run(
        transport="http",
        host=_HOST,
        port=_PORT,
        host_origin_protection=False,
    )


if __name__ == "__main__":
    main()
