"""Product data MCP server for the agentic banking ecosystem.

Exposes the bank's **financial product catalogue** (current accounts, savings,
children's savings and credit cards) together with the per-customer
``ProductHolding`` records, over the Model Context Protocol. The banking agents
(``customer_support_agent``, ``employee_advisory_agent``, ``credit_card_agent``)
use it to list and explain products, look up what a customer holds, order a new
product and update an existing holding.

Two data sources are loaded once at startup:

* the product catalogue in ``product_catalogue.json`` next to this module (a
  JSON mirror of the catalogue table in ``data/products.md``); and
* the per-customer holdings in the shared ``data/customers.json`` (generated by
  ``scripts/generate_data.py``).

There is no database — these files *are* the source of truth. Every MCP tool
call is expected to be authenticated via Entra ID, and all write tools are
human-in-the-loop. The canonical entities and tool surface are defined in
``data/products.md``.

Run it with::

    python -m src.product_data_mcp_server.server

It serves the streamable-HTTP MCP transport on ``http://127.0.0.1:8093/mcp`` by
default (override with ``PRODUCT_MCP_HOST`` / ``PRODUCT_MCP_PORT``).
"""

from __future__ import annotations

import copy
import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

from fastmcp import FastMCP
from starlette.requests import Request
from starlette.responses import JSONResponse

_CATALOGUE_FILE = Path(__file__).with_name("product_catalogue.json")


def _data_dir() -> Path:
    """Resolve the shared ``data/`` directory (repo root or ``BANK_DATA_DIR``)."""
    override = os.getenv("BANK_DATA_DIR")
    if override:
        return Path(override)
    # server.py -> product_data_mcp_server -> src -> <repo root>/data
    return Path(__file__).resolve().parents[2] / "data"


@lru_cache(maxsize=1)
def _catalogue() -> list[dict[str, Any]]:
    """Load and cache the product catalogue."""
    with _CATALOGUE_FILE.open("r", encoding="utf-8") as fh:
        return json.load(fh)["products"]


@lru_cache(maxsize=1)
def _customers() -> list[dict[str, Any]]:
    """Load and cache the customers (with nested product holdings)."""
    with (_data_dir() / "customers.json").open("r", encoding="utf-8") as fh:
        return json.load(fh)["customers"]


def _find_product(product_code: str) -> Optional[dict[str, Any]]:
    code = product_code.strip().upper()
    for product in _catalogue():
        if product["product_code"].upper() == code:
            return product
    # Fall back to a case-insensitive product-name match.
    name = product_code.strip().lower()
    for product in _catalogue():
        if product["product_name"].lower() == name:
            return product
    return None


def _find_customer(customer_id: str) -> Optional[dict[str, Any]]:
    cid = customer_id.strip().upper()
    return next((c for c in _customers() if c["customer_id"].upper() == cid), None)


def _find_holding(account_id: str) -> Optional[dict[str, Any]]:
    aid = account_id.strip().upper()
    for customer in _customers():
        for holding in customer.get("products", []):
            if holding["account_id"].upper() == aid:
                return holding
    return None


def _next_account_id() -> str:
    """Return the next free ``ACC-<6 digits>`` id across all customers."""
    highest = 100000
    for customer in _customers():
        for holding in customer.get("products", []):
            digits = holding["account_id"].split("-")[-1]
            if digits.isdigit():
                highest = max(highest, int(digits))
    return f"ACC-{highest + 1:06d}"


_HOST = os.getenv("PRODUCT_MCP_HOST", "127.0.0.1")
_PORT = int(os.getenv("PRODUCT_MCP_PORT", "8093"))


def _build_auth():
    """Build the FastMCP Microsoft Entra ID JWT auth provider, or ``None``.

    Enabled only when ``ENTRA_AUTH_ENABLED`` is truthy and both the API audience
    (``MCP_AUTH_CLIENT_ID``) and ``AZURE_TENANT_ID`` are set. The provider
    validates incoming Entra access tokens (issuer, audience and JWKS signature)
    inside the app itself — no Container Apps Easy Auth and no client secret.
    No scope is required, so both delegated (user) and app-only (managed
    identity) tokens are accepted. Returns ``None`` to run anonymously (local
    development, or auth toggled off).
    """
    enabled = os.getenv("ENTRA_AUTH_ENABLED", "false").strip().lower() in {
        "1", "true", "yes", "on",
    }
    client_id = os.getenv("MCP_AUTH_CLIENT_ID", "").strip()
    tenant_id = os.getenv("AZURE_TENANT_ID", "").strip()
    if not (enabled and client_id and tenant_id):
        return None
    from fastmcp.server.auth import RemoteAuthProvider
    from fastmcp.server.auth.providers.azure import AzureJWTVerifier
    from pydantic import AnyHttpUrl

    base_url = os.getenv("MCP_PUBLIC_BASE_URL", "").strip() or f"http://{_HOST}:{_PORT}"
    verifier = AzureJWTVerifier(client_id=client_id, tenant_id=tenant_id)
    return RemoteAuthProvider(
        token_verifier=verifier,
        authorization_servers=[
            AnyHttpUrl(f"https://login.microsoftonline.com/{tenant_id}/v2.0")
        ],
        base_url=base_url,
    )


mcp = FastMCP(
    name="product_data",
    instructions=(
        "Financial product catalogue and per-customer product holdings. Use "
        "these tools to list and explain products (current accounts, savings, "
        "children's savings, credit cards), look up what a customer holds, "
        "order a new product and update a holding. Interest rates are annual "
        "percentages and all monetary values are in EUR; detailed conditions "
        "are in the linked knowledge files. The 'order_product' and "
        "'update_holding' tools are write operations and require explicit human "
        "approval (human-in-the-loop) before they commit."
    ),
    auth=_build_auth(),
)


@mcp.custom_route("/health", methods=["GET"])
async def health_check(_: Request) -> JSONResponse:
    """Readiness probe endpoint — returns 200 OK when the server is up."""
    return JSONResponse({"status": "ok"})


@mcp.tool()
def list_products(category: Optional[str] = None) -> list[dict[str, Any]]:
    """List the financial product catalogue, optionally filtered by category.

    Args:
        category: Optional category filter — ``current_account``, ``savings``,
            ``childrens_savings`` or ``credit_card`` (case-insensitive). Omit to
            list every product.

    Each product includes its code, name, category, currency, annual interest
    rate, annual fee, minimum deposit and a reference to the knowledge file that
    documents its full conditions.
    """
    products = _catalogue()
    if category:
        needle = category.strip().lower()
        products = [p for p in products if p["category"] == needle]
    return copy.deepcopy(products)


@mcp.tool()
def get_product(product_code: str) -> dict[str, Any]:
    """Get a single product definition by code (or exact name).

    Args:
        product_code: The product code (e.g. ``GOLDCARD``) or exact product name
            (e.g. ``GoldCard``).

    Returns the product's catalogue fields including the ``knowledge_ref`` path
    that documents its conditions. If no product matches, an ``error`` field is
    returned instead.
    """
    product = _find_product(product_code)
    if product is None:
        return {"error": f"No product matched '{product_code}'."}
    return copy.deepcopy(product)


@mcp.tool()
def list_holdings(customer_id: str) -> list[dict[str, Any]]:
    """List the product holdings a customer currently has.

    Args:
        customer_id: The customer id, format ``CUST-1001``.

    Each holding includes the account id, product, IBAN or masked card number,
    balance, credit limit (cards) and status. Returns an empty list if the
    customer has no holdings or does not exist.
    """
    customer = _find_customer(customer_id)
    if customer is None:
        return []
    return copy.deepcopy(customer.get("products", []))


@mcp.tool()
def order_product(customer_id: str, product_code: str,
                  confirm: bool = False) -> dict[str, Any]:
    """Order a new product for a customer (write — human-in-the-loop).

    This is a **write** operation and requires explicit human approval. Call it
    first with ``confirm=False`` (the default) to receive a preview of the
    holding that would be opened; present that preview to the human and only
    re-call with ``confirm=True`` once approval has been granted.

    Args:
        customer_id: The customer id, format ``CUST-1001``.
        product_code: The product to order (e.g. ``GOLDCARD``).
        confirm: Set to ``True`` only after a human has approved the preview.

    Returns a ``pending_approval`` preview when ``confirm`` is ``False``, or the
    newly created holding once committed.
    """
    customer = _find_customer(customer_id)
    if customer is None:
        return {"error": f"No customer matched '{customer_id}'."}
    product = _find_product(product_code)
    if product is None:
        return {"error": f"No product matched '{product_code}'."}

    is_card = product["category"] == "credit_card"
    new_holding = {
        "account_id": _next_account_id(),
        "customer_id": customer["customer_id"],
        "product_code": product["product_code"],
        "product_name": product["product_name"],
        "category": product["category"],
        "iban": None if is_card else "PENDING-ASSIGNMENT",
        "card_number": "PENDING-ASSIGNMENT" if is_card else None,
        "balance": 0.0,
        "credit_limit": 1000 if is_card else None,
        "currency": product.get("currency", "EUR"),
        "status": "pending",
    }

    if not confirm:
        return {
            "status": "pending_approval",
            "customer_id": customer["customer_id"],
            "requires": "human approval (call again with confirm=true)",
            "proposed_holding": new_holding,
        }

    # Commit against the in-memory cache. The change lives for the life of the
    # process — deliberately not persisted to disk in this demo.
    new_holding["status"] = "active"
    customer.setdefault("products", []).append(
        {k: v for k, v in new_holding.items() if k != "customer_id"}
    )
    return {"status": "committed", "holding": new_holding}


# Fields a holding is allowed to change through this tool. Identity and money
# fields (account_id, customer_id, product_code, balance) are not editable here.
_EDITABLE_HOLDING_FIELDS = {"status", "credit_limit", "iban", "card_number"}


@mcp.tool()
def update_holding(account_id: str, fields: dict[str, Any],
                   confirm: bool = False) -> dict[str, Any]:
    """Update an existing product holding (write — human-in-the-loop).

    This is a **write** operation and requires explicit human approval. Call it
    first with ``confirm=False`` (the default) to receive a preview of the
    change; present that preview to the human and only re-call with
    ``confirm=True`` once approval has been granted. Only ``status``,
    ``credit_limit``, ``iban`` and ``card_number`` may be changed.

    Args:
        account_id: The account id, format ``ACC-100001``.
        fields: Mapping of field name to new value (subset of ``status``,
            ``credit_limit``, ``iban``, ``card_number``).
        confirm: Set to ``True`` only after a human has approved the preview.

    Returns a ``pending_approval`` preview when ``confirm`` is ``False``, or the
    updated holding once committed.
    """
    holding = _find_holding(account_id)
    if holding is None:
        return {"error": f"No account matched '{account_id}'."}

    invalid = set(fields) - _EDITABLE_HOLDING_FIELDS
    if invalid:
        return {
            "error": f"Fields not editable: {sorted(invalid)}.",
            "editable_fields": sorted(_EDITABLE_HOLDING_FIELDS),
        }
    if not fields:
        return {"error": "No fields supplied to update."}

    changes = {
        key: {"from": holding.get(key), "to": value}
        for key, value in fields.items()
    }

    if not confirm:
        return {
            "status": "pending_approval",
            "account_id": holding["account_id"],
            "requires": "human approval (call again with confirm=true)",
            "changes": changes,
        }

    holding.update(fields)
    return {"status": "committed", "holding": copy.deepcopy(holding),
            "changes": changes}


def main() -> None:
    """Entry point — serve the product data over streamable-HTTP MCP."""
    # ``host_origin_protection`` is FastMCP's DNS-rebinding guard for browser
    # clients hitting localhost dev servers; it rejects any Host header outside
    # 127.0.0.1/localhost with HTTP 421. This server runs behind the Container
    # Apps ingress (which routes by host) and is protected by Entra JWT auth, so
    # the guard is both unnecessary and would block the public FQDN + health
    # probe. Disable it and rely on the ingress + JWT verification instead.
    mcp.run(
        transport="http",
        host=_HOST,
        port=_PORT,
        host_origin_protection=False,
    )


if __name__ == "__main__":
    main()
